// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXL0tK1Min_1cbM68p4KkrQt8RLkbvtno',
    appId: '1:655969621888:web:cba8b12f0434b6c00c5365',
    messagingSenderId: '655969621888',
    projectId: 'alertzone-01',
    authDomain: 'alertzone-01.firebaseapp.com',
    storageBucket: 'alertzone-01.firebasestorage.app',
    measurementId: 'G-W13896CRHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3x5iIs_YCrAoDkbZaouHVUd1T9OzCYLI',
    appId: '1:655969621888:android:a45d5668140165b20c5365',
    messagingSenderId: '655969621888',
    projectId: 'alertzone-01',
    storageBucket: 'alertzone-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaQpE03lTqfPhLNJW7oiQMLx87qGt2yrQ',
    appId: '1:655969621888:ios:6d3b2c001ec3eaa30c5365',
    messagingSenderId: '655969621888',
    projectId: 'alertzone-01',
    storageBucket: 'alertzone-01.firebasestorage.app',
    iosBundleId: 'com.rafaelleonan.alertzone',
  );
}
